# Generated by Django 5.1.7 on 2025-03-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='family',
            unique_together={('family_name', 'inviter')},
        ),
    ]
