# Generated by Django 5.1.7 on 2025-04-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
    ]
