# Generated by Django 5.1.7 on 2025-04-08 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_child_parent'),
        ('families', '0002_remove_family_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='family',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='families.family'),
            preserve_default=False,
        ),
    ]
