# Generated by Django 5.1.7 on 2025-04-04 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='school_letters/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_letters', to='accounts.child')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_letters', to='families.family')),
            ],
        ),
    ]
