# Generated by Django 5.1.7 on 2025-04-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
