# Generated by Django 5.1.7 on 2025-04-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_all_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
