# Generated by Django 5.1.7 on 2025-03-27 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('shopping', '買い物'), ('cooking', '料理'), ('washing', '洗濯'), ('cleaning', '掃除'), ('hospital', '通院予定'), ('event', '行事予定'), ('other', 'その他')], max_length=20, null=True)),
                ('due_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('memo', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='task_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
